# CircleCI build config to test the Singularity Orb

version: 2.1

orbs:
  singularity: singularity/singularity@dev:alpha

executors:
  cli:
    resource_class: medium
    docker:
      - image: circleci/circleci-cli
  lint-condo:
    resource_class: medium
    docker:
      - image: singapore/lint-condo

jobs:
  lint:
    executor: lint-condo
    steps:
      - checkout
      - run: yamllint .

  validate:
    executor: cli
    steps:
      - checkout
      - run: circleci orb validate src/orb.yml


  test-install-alpine-docker-3:
    executor: singularity/alpine-docker
    steps:
      - checkout
      - singularity/alpine-install-3:
          singularity-version: 3.1-slim

  test-install-debian-2:
    executor: singularity/machine
    steps:
      - checkout
      - singularity/install-debian-2:
          singularity-version: 2.6.1


  test-install-debian-3:
    executor: singularity/machine
    steps:
      - checkout
      - singularity/install-debian-3:
          singularity-version: 3.1.0
          go-version: 1.11.5


  test-build-docker-base:
    executor: singularity/docker
    steps:
      - checkout
      - singularity/build-image-docker:
          singularity-version: 3.1-slim
          image: busybox.sif
          from-uri: docker://busybox

  test-build-docker-custom-3:
    executor: singularity/alpine-docker
    steps:
      - checkout
      - install-go:
          go-version: 11.1.5
      - alpine-install-3:
          singularity-version: 3.1.0
      - build-image-docker:
          from-uri: docker://busybox
          image: busybox.sif

  test-build-custom-2:
    executor: singularity/machine
    steps:
      - checkout
      - debian-install-2:
          singularity-version: 2.6.1
      - build-image-docker:
          from-uri: docker://busybox
          image: busybox.sif

  publish-dev:
    executor: cli
    steps:
      - checkout
      - run:
          name: publish dev versions
          command: |
            circleci orb publish src/orb.yml singularity/singularity@dev:alpha --token $CIRCLE_TOKEN
            circleci orb publish src/orb.yml singularity/singularity@dev:$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN
            circleci orb publish src/orb.yml singularity/singularity@dev:${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN

  dev-promote-prod:
    executor: cli
    steps:
      - checkout
      - run: circleci orb publish promote singularity/singularity@dev:${CIRCLE_SHA1:0:7} patch --token $CIRCLE_TOKEN

  publish:
    executor: cli
    steps:
      - checkout
      - run:
          name: publish production versions
          command: |
            VERSION=$(cat VERSION)
            circleci orb publish src/orb.yml singularity/singularity@${VERSION} --token $CIRCLE_TOKEN

workflows:
  validate_unit-test_dev-deploy:
    jobs:
      - lint

      - validate:
          requires:
            - lint

      - test-install-alpine-docker-3:
          requires:
            - validate

      - test-install-debian-2:
          requires:
            - validate

      - test-install-debian-3:
          requires:
            - validate

      - test-build-docker-base:
          requires:
            - validate

      - test-build-docker-custom-3:
          requires:
            - validate

      - test-build-custom-2:
          requires:
            - validate

      - publish-dev:
          requires:
            - test-install-alpine-docker-3
            - test-install-debian-2
            - test-install-debian-3
            - test-build-docker-base
            - test-build-docker-custom-3
            - test-build-custom-2

      - publish:
          requires:
            - test-install-alpine-docker-3
            - test-install-debian-2
            - test-install-debian-3
            - test-build-docker-base
            - test-build-docker-custom-3
            - test-build-custom-2
          filters:
             branches:
               only:
                 - master
