version: 2.1

description: >
  An orb for interacting with Singularity containers

# EXAMPLES ####################################################################
examples:
  simple_install:
    description: Install Singularity Version 3* and Up
    usage:
      version: 2.1

      orbs:
        singularity: singularity/singularity@1.0.0

      workflows:
        install_singularity_cli:
          executor: default
          jobs:
            - singularity/install_cli:
                singularity-version: 3.1.0

  docker_install:
    description: Use Singularity via a Docker container
    usage:
      version: 2.1

      orbs:
        singularity: singularity/singularity@1.0.0

      workflows:
        use_docker_cli:
          executor: docker
          jobs:
            - singularity/docker_cli:
                singularity-version: 3.1-slim


  simple_build:
    description: Build a Singularity Container
    usage:
      version: 2.1

      orbs:
        singularity: singularity/singularity@1.0.0

      workflows:
        build_singularity:
          executor: default
          jobs:
            - singularity/build_container:
                singularity-version: 3.1.0
                from-uri: docker://ubuntu
                image: ubuntu.sif


# EXECUTORS ####################################################################
# These are executors, the backend bases to run on
executors:
  machine:
    description: >
      A debian-based machine executor.
    machine: true
  default:
    description: >
      An alpine, go-lang base image that can have a custom Singularity install
    docker:
      - image: iron/go:dev
  docker:
    description: >
      Pre-build Docker container base to interact with Singularity
    parameters:
      singularity-version:
        type: string
        default: "3.1-slim"
    docker:
      - image: singularityware/singularity:<< parameters.singularity-version >>

# COMMANDS ####################################################################
# These are commands that can be given as steps to jobs
commands:
  install:
    description: |
      Install Singularity
    parameters:
      singularity-version:
        type: string
        default: "3.1.0"
    steps:
      - run:
          name: Install Singularity (Version 3.* and up)
          command: |
            apk update && \
            apk add --virtual automake build-base linux-headers libffi-dev
            apk add --no-cache bash git openssh gcc squashfs-tools sudo libtool gawk
            apk add --no-cache linux-headers build-base openssl-dev util-linux util-linux-dev
            export GOPATH=/go
            go get -u github.com/golang/dep/cmd/dep
            mkdir -p ${GOPATH}/src/github.com/sylabs
            cd ${GOPATH}/src/github.com/sylabs
            wget https://github.com/sylabs/singularity/releases/download/v<< parameters.singularity-version >>/singularity-<< parameters.singularity-version >>.tar.gz
            tar -xzvf singularity-<< parameters.singularity-version >>.tar.gz
            cd singularity && ./mconfig -p /usr/local && make -C builddir && $SUDO make -C builddir install

  install-version-2:
    description: |
      Install Singularity Versions 2.*
    parameters:
      singularity-version:
        type: string
        default: "2.6.1"
    steps:
      - run:
          name: Install Singularity (pre GoLang)
          command: |
            # The trick below is taken from circleci/gcp-cli, thanks!
            # Set sudo to work whether logged in as root user or non-root user
            if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
            $SUDO apt-get update && $SUDO apt-get -y install git \
                   build-essential \
                   libtool \
                   squashfs-tools \
                   autotools-dev \
                   libarchive-dev \
                   automake \
                   autoconf \
                   debootstrap \
                   yum \
                   uuid-dev \
                   libssl-dev \
                   python3-dev
            wget https://github.com/sylabs/singularity/releases/download/<< parameters.singularity-version >>/singularity-<< parameters.singularity-version >>.tar.gz
            tar -xzvf singularity-<< parameters.singularity-version >>.tar.gz
            cd singularity-<< parameters.singularity-version >> && ./autogen.sh && ./configure --prefix=/usr/local && make && $SUDO make install

  build-image:
    description: Build a Singularity container using default install (not Docker)
    parameters:
      from-uri:
        description: The Singularity recipe path or docker:// uri to build from.
        type: string
        default: Singularity
      image:
        description: The image binary to build (e.g., container.sif)
        type: string
        default: container.sif
    steps:
      - run:
          name: Build Singularity Container
          command: |
              if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi
              $SUDO singularity build <<parameters.image>> <<parameters.from-uri>>

  build-image-docker:
    description: Build a Singularity container using Docker
    parameters:
      singularity-version:
        type: string
        default: "3.1-slim"
      from-uri:
        description: The Singularity recipe path or docker:// uri to build from.
        type: string
        default: Singularity
      image:
        description: The image binary to build (e.g., container.sif)
        type: string
        default: container.sif
    steps:
      - run:
          name: Build Singularity Container
          command: |
              singularity build <<parameters.image>> <<parameters.from-uri>>

  inspect-image:
    description: Inspect a Singularity Container
    parameters:
      image:
        description: The image binary to inspect (e.g., container.sif)
        type: string
        default: container.sif
    steps:
      - run:
          name: Inspect Singularity Container
          command: |
            if [ -e "<< parameters.image >>" ]; then
                singularity inspect << parameters.image >>
            fi

jobs:
  install_cli:
    description: Install Singularity on the default executor.
    executor: default
    parameters:
      singularity-version:
        type: string
        default: "3.1.0"
    steps:
      - install:
          singularity-version: <<parameters.singularity-version>>
      - run: singularity --version

  docker_cli:
    description: Interact with Singularity via a Docker container
    executor: docker
    parameters:
      singularity-version:
        description: The Singularity version (tag on Docker Hub singularityware/singularity)
        type: string
        default: 3.1-slim
    steps:
      - run:
          name: Check Singularity Version
          singularity-version: <<parameters.singularity-version>>
          command: singularity --version

  build_container:
    description: Build a Singularity Container
    executor: default
    parameters:
      from-uri:
        description: The Singularity recipe path or docker:// uri to build from.
        type: string
        default: Singularity
      image:
        description: The image binary to build (e.g., container.sif)
        type: string
        default: container.sif
    steps:
      - install
      - build-image:
          from-uri: <<parameters.from-uri>>
          image: <<parameters.image>>
      - inspect-image:
          image: <<parameters.image>>

  build_container_version_2:
    description: Build a Singularity Container, pre goLang versions
    executor: machine
    parameters:
      from-uri:
        description: The Singularity recipe path or docker:// uri to build from.
        type: string
        default: Singularity
      image:
        description: The image binary to build (e.g., container.sif)
        type: string
        default: container.sif
    steps:
      - install-version-2
      - build-image:
          from-uri: <<parameters.from-uri>>
          image: <<parameters.image>>
      - inspect-image:
          image: <<parameters.image>>

  build_container_docker:
    description: Build a Singularity Container
    executor: docker
    parameters:
      from-uri:
        description: The Singularity recipe path or docker:// uri to build from.
        type: string
        default: Singularity
      image:
        description: The image binary to build (e.g., container.sif)
        type: string
        default: container.sif
    steps:
      - build-image-docker:
          from-uri: <<parameters.from-uri>>
          image: <<parameters.image>>
      - inspect-image:
          image: <<parameters.image>>
